#!/bin/sh
# RedHat startup script for a supervisor instance
#
# chkconfig: 2345 80 20
# description: a client/server system that allows monitoring and control of processes

# Source function library.
. /etc/rc.d/init.d/functions

bindir="/usr/bin"
supervisorctl="$bindir/supervisorctl"
supervisord="$bindir/supervisord"
name="supervisord"

[ -f $supervisord ] || exit 1
[ -f $supervisorctl ] || exit 1

RETVAL=0

start() {
        echo -n "Starting $name: "
        $supervisord
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$name
        echo
        return $RETVAL
}

stop() {
        echo -n "Stopping $name: "
        $supervisorctl shutdown
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$name
        echo
        return $RETVAL
}

reload() {
        echo -n "Reloading $name configuration: "
        $supervisorctl reread
        RETVAL=$?
        return $RETVAL
}

status() {
        echo "Current $name status:"
        $supervisorctl status
}

case "$1" in
        start)
                start
                ;;

        stop)
                stop
                ;;

        reload)
                reload
                ;;

        restart)
                stop
                start
                ;;

        status)
                status
                ;;

        *)
                echo $"Usage: $0 {start|stop|restart|reload|status}"
                RETVAL=1

esac

exit $REVAL

